language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
  - client/node_modules
script:
  - cd client && yarn install && yarn run lint --fix && yarn test && yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
